"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import VoiceChat from "@/app/voiceChat";
import { useCyberAudio } from "@/app/hooks/useCyberAudio";
// @ts-expect-error - Socket.io exports are bugged in this Next.js TS config.
import { io, Socket } from 'socket.io-client';

interface Flashcard {
  id: string;
  topic: string;
  question: string;
  answer: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
}

export default function LearnPage() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [flashcard, setFlashcard] = useState<Flashcard | null>(null);
  const [isAnswerRevealed, setIsAnswerRevealed] = useState(false);
  const { fadeOutMusic, playHover } = useCyberAudio();

  // Fade out music when Learn page opens
  useEffect(() => {
    fadeOutMusic();
  }, [fadeOutMusic]);
  const [agentUsername, setAgentUsername] = useState<string | undefined>(undefined);
  const [lobbyActive, setLobbyActive] = useState(true);
  const [roomName, setRoomName] = useState("training-room");
  const [privateCode, setPrivateCode] = useState("");
  const [joiningCode, setJoiningCode] = useState("");
  const [lobbyError, setLobbyError] = useState<string | null>(null);
  const [socket, setSocket] = useState<any>(null);

  useEffect(() => {
    const newSocket = io();
    setSocket(newSocket);
    return () => { newSocket.disconnect(); };
  }, []);

  useEffect(() => {
    if (socket && !lobbyActive) {
      socket.emit('join_global_room', roomName);
      
      const onFlashcardSync = (data: { flashcard: Flashcard, reveal: boolean }) => {
        setFlashcard(data.flashcard);
        setIsAnswerRevealed(data.reveal);
      };
      
      socket.on('flashcard_sync', onFlashcardSync);
      return () => { socket.off('flashcard_sync', onFlashcardSync); };
    }
  }, [socket, lobbyActive, roomName]);

  const fetchLesson = async (feedback?: 'up' | 'down') => {
    setLoading(true);
    setLobbyError(null);
    setError(null);
    setIsAnswerRevealed(false);
    try {
      const url = feedback ? `/api/learn?feedback=${feedback}` : '/api/learn';
      const response = await fetch(url);
      if (!response.ok) throw new Error("Failed to fetch intel");
      const data = await response.json();
      setFlashcard(data);
      if (socket && !lobbyActive) {
         socket.emit('broadcast_flashcard', { roomId: roomName, flashcard: data, reveal: false });
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Encryption mismatch error");
    } finally {
      setLoading(false);
    }
  };

  const handleRevealAnswer = () => {
    setIsAnswerRevealed(true);
    if (socket && !lobbyActive && flashcard) {
      socket.emit('broadcast_flashcard', { roomId: roomName, flashcard, reveal: true });
    }
  };

  useEffect(() => {
    fetchLesson();
    const storedUsername = localStorage.getItem("agentUsername");
    setAgentUsername(storedUsername || "");
  }, []);

  const handleJoinPublic = () => {
    setLobbyError(null);
    setRoomName("training-room");
    setLobbyActive(false);
  };

  const handleCreatePrivate = () => {
    setLobbyError(null);
    const code = Math.random().toString(36).substring(2, 8).toUpperCase();
    setPrivateCode(code);
    setRoomName(`private-${code}`);
    setLobbyActive(false);
  };

  const handleJoinPrivate = () => {
    if (joiningCode.trim().length === 6) {
      setLobbyError(null);
      setRoomName(`private-${joiningCode.toUpperCase()}`);
      setLobbyActive(false);
    } else {
      setLobbyError("INVALID_UPLINK_CODE: 6-digit ID required.");
    }
  };

  // Re-enable if needing livekit sync
  // const { send } = useDataChannel("flashcards");
  // const onMessage = (msg) => { setFlashcard(msg) };

  // Helper to safely render markdown bolding generated by Gemini
  const formatText = (text: string) => {
    const parts = text.split(/(\*\*.*?\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="text-cyber-green font-semibold">{part.slice(2, -2)}</strong>;
      }
      return <span key={i}>{part}</span>;
    });
  };

  return (
    <div className="min-h-screen bg-cyber-dark font-inter text-gray-200 selection:bg-cyber-blue selection:text-cyber-dark pb-20">
      {/* Background Decor */}
      <div className="fixed inset-0 z-0 opacity-10 pointer-events-none">
        <div
          className="absolute inset-0"
          style={{
            backgroundImage: `linear-gradient(rgba(0, 243, 255, 0.2) 1px, transparent 1px),
                              linear-gradient(90deg, rgba(0, 243, 255, 0.2) 1px, transparent 1px)`,
            backgroundSize: "50px 50px",
          }}
        />
        <div className="absolute top-0 left-0 w-96 h-96 bg-cyber-blue rounded-full mix-blend-screen filter blur-[150px] opacity-20"></div>
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-cyber-green rounded-full mix-blend-screen filter blur-[150px] opacity-10"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 py-8">
        <div className="flex items-center gap-4 mb-12">
          <Link href="/home" onMouseEnter={playHover} className="text-cyber-blue hover:text-glow-blue transition-all bg-cyber-darker border border-cyber-blue/30 rounded-lg p-2.5 filter flex items-center justify-center shadow-[0_0_15px_rgba(0,243,255,0.1)] hover:border-cyber-blue/60">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
          </Link>
          <h1 className="text-3xl md:text-4xl font-bold font-orbitron tracking-widest text-cyber-blue uppercase text-glow-blue">
            Training Ground
          </h1>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Left Column: Voice Chat */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-cyber-darker/80 border border-cyber-blue/30 rounded-xl p-6 backdrop-blur-md shadow-[0_0_20px_rgba(0,243,255,0.05)] sticky top-8">
              <h2 className="text-xl font-orbitron font-bold text-cyber-blue mb-4 flex items-center gap-2">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" /></svg>
                Comm Channel
              </h2>
              <p className="text-sm text-gray-400 mb-2">Coordinate with other agents to solve cyber problems together.</p>

              {privateCode && (
                <div className="mb-4 p-3 bg-cyber-blue/5 border border-cyber-blue/20 rounded-lg">
                  <p className="text-[10px] uppercase tracking-widest text-cyber-blue/60 mb-1 font-orbitron">Secure Uplink Code</p>
                  <p className="text-xl font-orbitron font-bold text-cyber-blue tracking-[0.2em]">{privateCode}</p>
                </div>
              )}

              <div className="border border-cyber-blue/20 rounded-xl p-1 bg-cyber-dark/50 min-h-[50px] flex items-center justify-center">
                {agentUsername !== undefined && !lobbyActive ? (
                  <VoiceChat roomName={roomName} username={agentUsername || undefined} />
                ) : (
                  <span className="text-cyber-blue text-sm animate-pulse">Waiting for Uplink Selection...</span>
                )}
              </div>
            </div>
          </div>

          {/* Right Column: Reading Material & Discovery Lobby */}
          <div className="lg:col-span-8 flex flex-col relative">
            {lobbyActive ? (
              <div className="bg-cyber-dark/95 backdrop-blur-md rounded-2xl border border-cyber-blue/30 p-8 flex flex-col items-center justify-center text-center animate-fade-in relative z-50 mt-8">
                <div className="mb-8 relative">
                  <div className="absolute inset-0 bg-cyber-blue/20 blur-3xl rounded-full"></div>
                  <svg className="w-20 h-20 text-cyber-blue relative z-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
                </div>

                <h2 className="text-3xl font-orbitron font-bold text-white mb-2 tracking-widest uppercase">Discovery Lobby</h2>
                <p className="text-cyber-blue/60 mb-6 font-medium">Select your initialization mode to decrypt the intelligence briefing.</p>

                {lobbyError && (
                  <div className="mb-6 p-3 bg-red-500/10 border border-red-500/30 rounded-lg animate-shake">
                    <p className="text-xs font-orbitron text-red-500 uppercase tracking-tight">{lobbyError}</p>
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full max-w-2xl">
                  {/* Public Party */}
                  <button
                    onClick={handleJoinPublic}
                    className="p-6 bg-cyber-darker border border-cyber-blue/30 rounded-xl hover:border-cyber-blue hover:box-glow-blue transition-all group text-left"
                  >
                    <h3 className="text-lg font-orbitron font-bold text-cyber-blue mb-2 uppercase tracking-wider group-hover:text-glow-blue">Public Party</h3>
                    <p className="text-xs text-gray-400">Join the main decrypt stream with other active agents.</p>
                  </button>

                  {/* Create Private */}
                  <button
                    onClick={handleCreatePrivate}
                    className="p-6 bg-cyber-darker border border-cyber-green/30 rounded-xl hover:border-cyber-green hover:box-glow-green transition-all group text-left"
                  >
                    <h3 className="text-lg font-orbitron font-bold text-cyber-green mb-2 uppercase tracking-wider group-hover:text-glow-green">Create Private</h3>
                    <p className="text-xs text-gray-400">Initialize a custom enclave and share the uplink code.</p>
                  </button>

                  {/* Join Private */}
                  <div className="md:col-span-2 p-6 bg-cyber-darker border border-cyber-blue/20 rounded-xl flex flex-col sm:flex-row gap-4 items-center">
                    <div className="flex-1">
                      <h3 className="text-lg font-orbitron font-bold text-white mb-1 uppercase tracking-wider">Join Private</h3>
                      <p className="text-xs text-gray-400">Enter a 6-digit secure uplink code.</p>
                    </div>
                    <div className="flex flex-col gap-2 w-full sm:w-auto">
                      <div className="flex gap-2">
                        <input
                          type="text"
                          maxLength={6}
                          placeholder="CODE_ID"
                          value={joiningCode}
                          onChange={(e) => {
                            setJoiningCode(e.target.value.toUpperCase());
                            if (lobbyError) setLobbyError(null);
                          }}
                          className={`bg-cyber-dark border ${lobbyError ? 'border-red-500/50' : 'border-cyber-blue/30'} rounded-lg px-4 py-2 font-orbitron text-cyber-blue focus:border-cyber-blue focus:outline-none w-32 tracking-widest text-center`}
                        />
                        <button
                          onClick={handleJoinPrivate}
                          className="bg-cyber-blue/10 border border-cyber-blue text-cyber-blue px-6 py-2 rounded-lg font-orbitron font-bold uppercase text-xs hover:bg-cyber-blue hover:text-cyber-dark transition-all"
                        >
                          Uplink
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}

            {/* Render flashcards when we are not in the lobby */}
            {!lobbyActive && (
              <InteractiveLearnSession 
                flashcard={flashcard} 
                setFlashcard={setFlashcard}
                isAnswerRevealed={isAnswerRevealed}
                setIsAnswerRevealed={setIsAnswerRevealed}
                handleRevealAnswer={handleRevealAnswer}
                loading={loading}
                error={error}
                fetchLesson={fetchLesson}
                formatText={formatText}
                playHover={playHover}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function InteractiveLearnSession({
  flashcard, setFlashcard, isAnswerRevealed, setIsAnswerRevealed, handleRevealAnswer, loading, error, fetchLesson, formatText, playHover
}: {
  flashcard: Flashcard | null,
  setFlashcard: React.Dispatch<React.SetStateAction<Flashcard | null>>,
  isAnswerRevealed: boolean,
  setIsAnswerRevealed: React.Dispatch<React.SetStateAction<boolean>>,
  handleRevealAnswer: () => void,
  loading: boolean,
  error: string | null,
  fetchLesson: (feedback?: 'up' | 'down') => Promise<void>,
  formatText: (text: string) => (React.JSX.Element | React.JSX.Element)[],
  playHover: () => void
}) {
  // Sync the flashcard object over the network using WebSockets or LiveKit if possible.
  // Since we don't have a child LiveKitRoom context here (VoiceChat creates its own inner room), 
  // we will leave flashcards locally decoupled from LiveKit audio right now, 
  // OR we can implement socket.io but that will take longer. I will implement a simpler sync if available.

  return (
    <div className="bg-cyber-darker/60 border border-cyber-green/30 rounded-2xl p-8 backdrop-blur-xl shadow-[0_0_50px_rgba(0,255,100,0.05)] relative overflow-hidden group min-h-[400px] transition-all duration-700 mt-8">
      <div className="absolute top-0 right-0 w-64 h-64 bg-cyber-green/10 rounded-full mix-blend-screen filter blur-[80px] pointer-events-none group-hover:bg-cyber-green/20 transition-all duration-700"></div>

              <div className="flex justify-between items-center mb-8 border-b border-cyber-green/20 pb-6 relative z-10">
                <h2 className="text-2xl font-orbitron font-bold text-cyber-green tracking-wider uppercase flex items-center gap-3 text-glow-green">
                  <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>
                  Intelligence Briefing
                </h2>
                <button
                  onClick={() => fetchLesson()}
                  onMouseEnter={playHover}
                  className="bg-cyber-dark border border-cyber-green text-cyber-green px-5 py-2.5 rounded-lg font-orbitron text-sm font-bold uppercase tracking-wider hover:bg-cyber-green hover:text-cyber-dark hover:box-glow-green shadow-[0_0_15px_rgba(0,255,100,0.1)] transition-all duration-300 flex items-center gap-2"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
                  Generate Intel
                </button>
              </div>

              <div className="relative z-10">
                {loading ? (
                  <div className="flex flex-col items-center justify-center py-20 gap-6">
                    <div className="relative w-24 h-24 flex items-center justify-center">
                      <div className="absolute inset-0 rounded-full border-t-2 border-b-2 border-cyber-green animate-spin"></div>
                      <div className="absolute inset-2 rounded-full border-r-2 border-l-2 border-cyber-blue animate-spin animate-reverse"></div>
                      <span className="text-3xl text-cyber-green text-glow-green animate-pulse">📡</span>
                    </div>
                    <p className="text-cyber-green animate-pulse font-orbitron tracking-widest uppercase text-sm">Intercepting Phishing Intel...</p>
                  </div>
                ) : error ? (
                  <div className="bg-red-500/10 border border-red-500/50 rounded-xl p-8 text-center backdrop-blur-lg">
                    <span className="text-4xl mb-4 block">⚠️</span>
                    <h2 className="font-orbitron text-red-500 font-bold tracking-widest uppercase mb-2">Decryption Failed</h2>
                    <p className="text-red-400 text-sm">{error}</p>
                  </div>
                ) : flashcard ? (
                  <article className="space-y-10 animate-fade-in-up">
                    <header className="mb-8 border-b border-cyber-blue/30 pb-4">
                      <div className="flex justify-between items-center mb-2">
                        <span className="text-cyber-blue font-orbitron font-bold uppercase tracking-widest text-sm bg-cyber-blue/10 px-3 py-1 rounded">
                          {flashcard.topic}
                        </span>
                        <span className={`font-mono text-xs font-bold uppercase ${flashcard.difficulty === 'Advanced' ? 'text-red-500' : flashcard.difficulty === 'Intermediate' ? 'text-yellow-500' : 'text-green-500'}`}>
                          [{flashcard.difficulty}]
                        </span>
                      </div>
                      <h1 className="text-2xl font-bold font-inter text-white line-clamp-3">
                        {flashcard.question}
                      </h1>
                    </header>

                    <div className="space-y-6">
                      {!isAnswerRevealed ? (
                        <div className="flex justify-center">
                          <button
                            onClick={handleRevealAnswer}
                            onMouseEnter={playHover}
                            className="bg-cyber-blue/20 hover:bg-cyber-blue border border-cyber-blue text-cyber-blue hover:text-black py-3 px-8 rounded-lg font-orbitron font-bold uppercase tracking-wider transition-all"
                          >
                            Reveal Intel
                          </button>
                        </div>
                      ) : (
                        <div className="bg-[#050A1F] p-8 rounded-xl border border-cyber-green/50 shadow-[0_0_20px_rgba(0,255,100,0.1)] relative">
                          <h3 className="text-cyber-green font-orbitron text-xs font-bold uppercase tracking-[0.2em] mb-4">Classified Answer:</h3>
                          <p className="text-gray-200 leading-relaxed text-lg">
                            {formatText(flashcard.answer)}
                          </p>
                          
                          <div className="flex justify-end gap-4 mt-8 pt-6 border-t border-cyber-green/20">
                            <button
                              onClick={() => fetchLesson('down')}
                              title="Too Hard - Make it Easier"
                              className="text-gray-400 hover:text-red-500 hover:bg-red-500/10 p-3 rounded-full transition-colors flex items-center gap-2 font-orbitron text-xs font-bold uppercase"
                            >
                              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 14H5.236a2 2 0 01-1.789-2.894l3.5-7A2 2 0 018.736 3h4.018a2 2 0 01.485.06l3.76.94m-7 10v5a2 2 0 002 2h.096c.5 0 .905-.405.905-.904 0-.715.211-1.413.608-2.008L17 13V4m-7 10h2m5-10h2a2 2 0 012 2v6a2 2 0 01-2 2h-2.5" /></svg>
                              Easier
                            </button>
                            <button
                              onClick={() => fetchLesson('up')}
                              title="Too Easy - Make it Harder"
                              className="text-gray-400 hover:text-green-500 hover:bg-green-500/10 p-3 rounded-full transition-colors flex items-center gap-2 font-orbitron text-xs font-bold uppercase"
                            >
                              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" /></svg>
                              Harder
                            </button>
                          </div>
                        </div>
                      )}
                    </div>
                  </article>
                ) : null}

                {/* Transition to Trivia Module */}
                {!loading && !error && flashcard && (
                  <div className="mt-16 pt-12 border-t border-cyber-blue/20 relative animate-fade-in-up">
                    <div className="absolute -top-px left-1/2 -translate-x-1/2 w-64 h-px bg-linear-to-r from-transparent via-cyber-blue to-transparent"></div>
                    <div className="text-center space-y-6 bg-cyber-dark/80 backdrop-blur-md p-8 sm:p-12 rounded-2xl border border-cyber-blue/40 shadow-[0_0_30px_rgba(0,243,255,0.05)]">
                      <h2 className="text-2xl sm:text-3xl font-orbitron font-bold text-white uppercase tracking-widest text-glow-blue">
                        Training Complete
                      </h2>
                      <p className="text-cyber-green/80 text-lg max-w-2xl mx-auto">
                        You&apos;ve absorbed the intelligence. Now, test your reaction time and knowledge under pressure in the Live Fire Trivia Simulation.
                      </p>
                      <div className="pt-4">
                        <Link
                          href="/trivia"
                          onMouseEnter={playHover}
                          className="inline-flex items-center gap-3 px-8 py-4 bg-cyber-blue/10 border-2 border-cyber-blue text-cyber-blue font-orbitron font-bold tracking-widest uppercase rounded-lg hover:bg-cyber-blue hover:text-cyber-dark hover:box-glow-blue transition-all duration-300 group"
                        >
                          Initiate Trivia Protocol
                          <svg className="w-5 h-5 group-hover:translate-x-2 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" /></svg>
                        </Link>
                      </div>
                    </div>
                  </div>
                )}
              </div>
    </div>
  );
}
