"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import VoiceChat from "@/app/voiceChat";

interface ContentBlock {
  id: number;
  text: string;
}

interface MCQOption {
  id: string;
  text: string;
}

interface DiscussionQuestion {
  id: number;
  insertAfterBlockId: number;
  question: string;
  options: MCQOption[];
  correctOptionId: string;
  explanation: string;
}

interface LessonData {
  title: string;
  description: string;
  contentBlocks: ContentBlock[];
  discussionQuestions: DiscussionQuestion[];
}

export default function LearnPage() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lessonData, setLessonData] = useState<LessonData | null>(null);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string>>({});

  const fetchLesson = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/learn");
      if (!res.ok) {
        throw new Error("Failed to initialize secure data stream.");
      }
      const text = await res.text();
      const data = JSON.parse(text) as LessonData;
      
      // Ensure data matches expected format before setting
      if (data.title && data.contentBlocks) {
         setLessonData(data);
      } else {
         throw new Error("Received malformed data packet.");
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error parsing data stream.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLesson();
  }, []);

  const handleSelectOption = (questionId: number, optionId: string) => {
    // Only allow selecting if they haven't answered yet
    if (!selectedAnswers[questionId]) {
      setSelectedAnswers(prev => ({
        ...prev,
        [questionId]: optionId
      }));
    }
  };

  // Helper to safely render markdown bolding generated by Gemini
  const formatText = (text: string) => {
    const parts = text.split(/(\*\*.*?\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="text-cyber-green font-semibold">{part.slice(2, -2)}</strong>;
      }
      return <span key={i}>{part}</span>;
    });
  };

  return (
    <div className="min-h-screen bg-cyber-dark font-inter text-gray-200 selection:bg-cyber-blue selection:text-cyber-dark pb-20">
      {/* Background Decor */}
      <div className="fixed inset-0 z-0 opacity-10 pointer-events-none">
        <div 
          className="absolute inset-0"
          style={{
            backgroundImage: `linear-gradient(rgba(0, 243, 255, 0.2) 1px, transparent 1px),
                              linear-gradient(90deg, rgba(0, 243, 255, 0.2) 1px, transparent 1px)`,
            backgroundSize: "50px 50px",
          }}
        />
        <div className="absolute top-0 left-0 w-96 h-96 bg-cyber-blue rounded-full mix-blend-screen filter blur-[150px] opacity-20"></div>
        <div className="absolute bottom-0 right-0 w-96 h-96 bg-cyber-green rounded-full mix-blend-screen filter blur-[150px] opacity-10"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 py-8">
        <div className="flex items-center gap-4 mb-12">
          <Link href="/home" className="text-cyber-blue hover:text-glow-blue transition-all bg-cyber-darker border border-cyber-blue/30 rounded-lg p-2.5 filter flex items-center justify-center shadow-[0_0_15px_rgba(0,243,255,0.1)] hover:border-cyber-blue/60">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
          </Link>
          <h1 className="text-3xl md:text-4xl font-bold font-orbitron tracking-widest text-cyber-blue uppercase text-glow-blue">
            Training Ground
          </h1>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Left Column: Voice Chat */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-cyber-darker/80 border border-cyber-blue/30 rounded-xl p-6 backdrop-blur-md shadow-[0_0_20px_rgba(0,243,255,0.05)] sticky top-8">
              <h2 className="text-xl font-orbitron font-bold text-cyber-blue mb-4 flex items-center gap-2">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" /></svg>
                Comm Channel
              </h2>
              <p className="text-sm text-gray-400 mb-6">Coordinate with other agents to solve cyber problems together.</p>
              
              <div className="border border-cyber-blue/20 rounded-xl p-1 bg-cyber-dark/50">
                <VoiceChat roomName="training-room" />
              </div>
            </div>
          </div>

          {/* Right Column: Reading Material & Discussion Questions */}
          <div className="lg:col-span-8 flex flex-col">
            <div className="bg-cyber-darker/60 border border-cyber-green/30 rounded-2xl p-8 backdrop-blur-xl shadow-[0_0_50px_rgba(0,255,100,0.05)] relative overflow-hidden group min-h-[400px]">
              <div className="absolute top-0 right-0 w-64 h-64 bg-cyber-green/10 rounded-full mix-blend-screen filter blur-[80px] pointer-events-none group-hover:bg-cyber-green/20 transition-all duration-700"></div>
              
              <div className="flex justify-between items-center mb-8 border-b border-cyber-green/20 pb-6 relative z-10">
                <h2 className="text-2xl font-orbitron font-bold text-cyber-green tracking-wider uppercase flex items-center gap-3 text-glow-green">
                  <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>
                  Intelligence Briefing
                </h2>
                <button 
                  onClick={fetchLesson}
                  className="bg-cyber-dark border border-cyber-green text-cyber-green px-5 py-2.5 rounded-lg font-orbitron text-sm font-bold uppercase tracking-wider hover:bg-cyber-green hover:text-cyber-dark hover:box-glow-green shadow-[0_0_15px_rgba(0,255,100,0.1)] transition-all duration-300 flex items-center gap-2"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
                  Generate Intel
                </button>
              </div>

              <div className="relative z-10">
                {loading ? (
                  <div className="flex flex-col items-center justify-center py-20 gap-6">
                    <div className="relative w-24 h-24 flex items-center justify-center">
                      <div className="absolute inset-0 rounded-full border-t-2 border-b-2 border-cyber-green animate-spin"></div>
                      <div className="absolute inset-2 rounded-full border-r-2 border-l-2 border-cyber-blue animate-spin animate-reverse"></div>
                      <span className="text-3xl text-cyber-green text-glow-green animate-pulse">📡</span>
                    </div>
                    <p className="text-cyber-green animate-pulse font-orbitron tracking-widest uppercase text-sm">Intercepting Phishing Intel...</p>
                  </div>
                ) : error ? (
                   <div className="bg-red-500/10 border border-red-500/50 rounded-xl p-8 text-center backdrop-blur-lg">
                    <span className="text-4xl mb-4 block">⚠️</span>
                    <h2 className="font-orbitron text-red-500 font-bold tracking-widest uppercase mb-2">Decryption Failed</h2>
                    <p className="text-red-400 text-sm">{error}</p>
                   </div>
                ) : lessonData ? (
                  <article className="space-y-10 animate-fade-in-up">
                    <header className="mb-8">
                      <h1 className="text-3xl font-bold font-orbitron text-white uppercase tracking-wider mb-3">
                        {lessonData.title}
                      </h1>
                      <p className="text-cyber-green/80 text-lg">
                        {lessonData.description}
                      </p>
                    </header>

                    <div className="space-y-12">
                      {lessonData.contentBlocks.map((block) => {
                        const relatedQuestion = lessonData.discussionQuestions?.find(
                          (q) => q.insertAfterBlockId === block.id
                        );

                        return (
                          <section key={`block-${block.id}`} className="space-y-8">
                            
                            {/* Lesson Text */}
                            <div className="bg-[#050A1F] p-6 rounded-xl border border-cyber-blue/20 shadow-inner">
                              <p className="text-gray-300 leading-relaxed text-lg">
                                {formatText(block.text)}
                              </p>
                            </div>

                            {/* Interactive Discussion Question */}
                            {relatedQuestion && (
                              <div className="pl-4 sm:pl-8 border-l-2 border-cyber-green/50">
                                <div className="bg-cyber-dark/80 border border-cyber-green-dim rounded-xl overflow-hidden shadow-[0_0_20px_rgba(0,255,157,0.05)]">
                                  
                                  {/* Question Header */}
                                  <div className="bg-cyber-green/5 border-b border-cyber-green/10 p-4 flex items-center gap-3">
                                    <span className="text-cyber-green text-xl animate-pulse">💬</span>
                                    <h3 className="font-orbitron font-semibold text-cyber-green tracking-wider uppercase text-sm">
                                      Agent Discussion Target
                                    </h3>
                                  </div>
                                  
                                  {/* Question Text */}
                                  <div className="p-5 sm:p-6 space-y-5">
                                    <p className="text-white font-medium text-lg leading-snug">
                                      {relatedQuestion.question}
                                    </p>
                                    
                                    {/* MCQ Options */}
                                    <div className="grid grid-cols-1 gap-3 mt-4">
                                      {relatedQuestion.options.map((opt) => {
                                        const isSelected = selectedAnswers[relatedQuestion.id] === opt.id;
                                        const isAnswered = !!selectedAnswers[relatedQuestion.id];
                                        const isCorrect = opt.id === relatedQuestion.correctOptionId;
                                        
                                        // Determine styling based on state
                                        let btnStyle = "bg-cyber-dark border-cyber-green/30 text-cyber-green/80 hover:bg-cyber-green/10";
                                        
                                        if (isAnswered) {
                                          if (isCorrect) {
                                            btnStyle = "bg-cyber-green/20 border-cyber-green text-cyber-green shadow-[0_0_15px_rgba(0,255,157,0.2)]"; // Correct answer glows green
                                          } else if (isSelected && !isCorrect) {
                                            btnStyle = "bg-red-500/20 border-red-500 text-red-500"; // Wrong selection turns red
                                          } else {
                                            btnStyle = "bg-cyber-dark border-cyber-green/10 text-cyber-green/30 opacity-50"; // Unselected wrong answers dim
                                          }
                                        }

                                        return (
                                          <button
                                            key={opt.id}
                                            onClick={() => handleSelectOption(relatedQuestion.id, opt.id)}
                                            disabled={isAnswered}
                                            className={`
                                              w-full text-left px-5 py-4 rounded-lg border transition-all duration-300 flex items-start gap-4
                                              ${btnStyle}
                                            `}
                                          >
                                            <span className="font-orbitron font-bold text-lg leading-none">{opt.id}</span>
                                            <span className="leading-snug">{opt.text}</span>
                                          </button>
                                        );
                                      })}
                                    </div>

                                    {/* Answer Payload Explanation */}
                                    <div 
                                      className={`
                                        overflow-hidden transition-all duration-500 ease-in-out border-l-2
                                        ${selectedAnswers[relatedQuestion.id] === relatedQuestion.correctOptionId ? 'border-cyber-green' : 'border-red-500'}
                                        ${selectedAnswers[relatedQuestion.id] ? "max-h-96 opacity-100 mt-6 pl-4" : "max-h-0 opacity-0"}
                                      `}
                                    >
                                      <div className="pt-2 text-gray-300 text-md">
                                        <span className={`font-orbitron font-bold mr-2 not-italic text-xs ${selectedAnswers[relatedQuestion.id] === relatedQuestion.correctOptionId ? 'text-cyber-green' : 'text-red-500'}`}>
                                          {selectedAnswers[relatedQuestion.id] === relatedQuestion.correctOptionId ? 'MISSION SUCCESS:' : 'MISSION FAILED:'}
                                        </span> 
                                        {relatedQuestion.explanation}
                                      </div>
                                    </div>

                                  </div>
                                </div>
                              </div>
                            )}
                          </section>
                        );
                      })}
                    </div>
                  </article>
                ) : null}

                {/* Transition to Trivia Module */}
                {!loading && !error && lessonData && (
                  <div className="mt-16 pt-12 border-t border-cyber-blue/20 relative animate-fade-in-up">
                    <div className="absolute -top-px left-1/2 -translate-x-1/2 w-64 h-px bg-linear-to-r from-transparent via-cyber-blue to-transparent"></div>
                    <div className="text-center space-y-6 bg-cyber-dark/80 backdrop-blur-md p-8 sm:p-12 rounded-2xl border border-cyber-blue/40 shadow-[0_0_30px_rgba(0,243,255,0.05)]">
                       <h2 className="text-2xl sm:text-3xl font-orbitron font-bold text-white uppercase tracking-widest text-glow-blue">
                         Training Complete
                       </h2>
                       <p className="text-cyber-green/80 text-lg max-w-2xl mx-auto">
                         You&apos;ve absorbed the intelligence. Now, test your reaction time and knowledge under pressure in the Live Fire Trivia Simulation.
                       </p>
                       <div className="pt-4">
                         <Link 
                           href="/trivia"
                           className="inline-flex items-center gap-3 px-8 py-4 bg-cyber-blue/10 border-2 border-cyber-blue text-cyber-blue font-orbitron font-bold tracking-widest uppercase rounded-lg hover:bg-cyber-blue hover:text-cyber-dark hover:box-glow-blue transition-all duration-300 group"
                         >
                           Initiate Trivia Protocol
                           <svg className="w-5 h-5 group-hover:translate-x-2 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" /></svg>
                         </Link>
                       </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
